apps/activity/urls.py
from django.conf.urls import patterns, url
from activity import views

urlpatterns = [
   url(r'^event/(?P<content_id>\d+)/(?P<object_id>\d+)/$', views.event_update, name='event_update'),
]

apps/projects/urls.py
from django.conf.urls import patterns, url, include

from med_social.decorators import (member_required, vendor_required, client_required)

from .views import (CreateProject, UpdateProject, ProjectDetails,
                    ProjectBudget, SendProposalView, budget_details,project_list,
                    my_project_list, staffing_confirmation, add_user_to_project,
                    share_project, change_proposed_status, invite_users)


urlpatterns = patterns('projects.views',
    url(r'^$', project_list, name='list'),
    url(r'^my/$', my_project_list, name='my_list'),
    url(r'^create/$', member_required(CreateProject.as_view()), name='create'),
    url(r'^(?P<pk>\d+)/$', member_required(ProjectDetails.as_view()),
        name='detail'),
    url(r'^(?P<pk>\d+)/users/add/$', add_user_to_project,
        name='add_user'),
    url(r'^(?P<pk>\d+)/budget/$', member_required(ProjectBudget.as_view()),
        name='budget_label'),
    url(r'^(?P<pk>\d+)/budget/details/$', budget_details,
        name='budget_details'),
    url(r'^(?P<pk>\d+)/edit/$', UpdateProject.as_view(), name='edit'),
    #url(r'^(?P<pk>\d+)/status/edit/$', 'update_project_status', name='edit_status'),
    url(r'^(?P<project_pk>\d+)/proposed/(?P<pk>\d+)/status/$',
        change_proposed_status,
        name='change_proposed_status'
    ),
    url('responses/send_proposal/(?P<pk>\d+)/$',
        vendor_required(SendProposalView.as_view()),
        name='send_proposal'
    ),
    url('users/invite/$', invite_users, name='invite_users'),
    url('status/', include('projects.status_urls', namespace='status')),
    url(r'^confirm/(?P<sr_pk>\d+)/(?P<answer>\d+)/$',
        vendor_required(staffing_confirmation),
        name='staffing_confirmation'),
    url(r'^(?P<project_pk>\d+)/team/$',
        client_required(share_project),
        name='share_project'),
)

apps/rates/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    url(r'^$', views.rate_list, name='list'),
    url(r'^(?P<pk>\d+)/$', views.rate_as_field, name='as_field'),
    url(r'^suggestions/$', views.suggestions, name='suggestions'),
    url(r'^create/$', views.create_rate, name='create'),
    #url(r'^user_rate/(?P<username>[\w\s@+.-]+)/$', views.edit_user_rate, name='edit_user_rate'),
    url(r'^(?P<pk>\d+)/edit/$', views.edit_rate, name='edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete_rate, name='delete'),
]

med_social/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.conf import settings

from allauth.account.views import LoginView
from djangosaml2.views import echo_attributes
from mailviews import previews
previews.autodiscover()

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from notifications import urls as notifications_urls
admin.autodiscover()

from users.forms import CustomLoginForm
from .views import WaitListView, InviteView, InviteApplyView, About
from .decorators import member_required, client_required
from .admin import site as admin_site

urlpatterns = [
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^emails/', include(previews.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    # We overrided some variables in allauth's original form implementation
    url(r'^accounts/login/$',
        LoginView.as_view(form_class=CustomLoginForm),
        name="account_login"),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^waitlist/$', login_required(WaitListView.as_view()), name='waitlist'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact_us.html'), name='contact_us'),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'^invite/$', member_required(InviteView.as_view()), name='invite'),
    url(r'^apply/@(?P<username>%s)/$' % settings.ACCOUNT_USERNAME_REGEX, InviteApplyView.as_view(), name='invite_link'),

    url(r'^api/', include('API.urls', namespace='api')),

    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^staffing/', include('projects.staffing_urls', namespace='staffing')),
    url(r'^availability/', include('availability.urls', namespace='availability')),
    url(r'^vendors/', include('vendors.urls', namespace='vendors')),
    url(r'^u/', include('users.setup_urls', namespace='user_setup')),
    url(r'^metrics/', include('reviews.metric_urls', namespace='metrics')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^notes/', include('notes.urls', namespace='notes')),
    url(r'^services/', include('services.urls.vendors', namespace='services')),
    url(r'^groups/', include('ACL.urls', namespace='groups')),
    url(r'^notifications/', include(notifications_urls)),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^rates/', include('rates.urls', namespace='rates')),
    url(r'^channels/', include('channels.urls', namespace='channels')),
    url(r'^suggest/', include('core.suggestions_urls', namespace='suggestions')),
    url(r'^a/', include('analytics.urls', namespace='analytics')),
    url(r'^locations/', include('locations.urls', namespace='locations')),
    url(r'^divisions/', include('divisions.urls', namespace='divisions')),
    url(r'^clients/', include('clients.urls', namespace='clients')),
    url(r'', include('customers.urls')),
    url(r'^activity/', include('activity.urls', namespace='activity')),
    url(r'^blog/', include('posts.urls', namespace='posts')),
    url(r'^payments/', include('djstripe.urls', namespace='djstripe')),
    url(r'^saml2/', include('djangosaml2.urls')),
    url(r'^test/', echo_attributes),
    url(r'^rfp/', include('lightrfp.urls')),
]

# Serve static files in development
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

admin.site.login = admin_site.login

# Usefull for testing prod environment locally without nginx
#urlpatterns += patterns('',
#   url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
#       'document_root': settings.STATIC_ROOT,
#   }),
#)

apps/projects/views/projects.py
from datetime import date, timedelta

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
from django.db import transaction, connection
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.contrib.humanize.templatetags.humanize import intcomma
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.views.generic import (View, DetailView, ListView, FormView,
                                  TemplateView, DeleteView, UpdateView,
                                  CreateView)
from annoying.functions import get_object_or_None
from urlobject import URLObject

from med_social.utils import today


from med_social.views.base import BaseEditView
from med_social.decorators import (client_required,
                                   member_required)

from users.models import UserDivisionRel
from vendors.models import Vendor
from rates.models import Rate
from channels.models import Channel
from rates.forms import SuggestedRateForm
from channels.forms import NewChannelForm, MessageForm
from activity.models import Event
from features import models as features
from ..forms import (ProjectForm,
                     StaffingResponseForm,
                     FixedResponseForm,
                     ProposeResourceForm,
                     SendProposalForm,
                     ProposedStatusButtonForm,
                     SuggestedResourcesForm,
                     ProjectInviteForm,
                     StaffignConfirmationForm,
                     StaffingBasicForm,
                     DeliverableResponseForm,
                     ProjectStaffForm,
                     ShareProjectForm,
                     UpdateProposeResourceForm)

from ..models import (Project,
                      StaffingRequest,
                      StaffingResponse,
                      ProposedResourceStatus,
                      ProposedResource,
                      RequestVendorRelationship,
                      RequestVendorRelationship,
                      DeliverableResponse)
from ..tasks import request_info_task, sr_confirmation, share_project_mail
from ..filters import ProjectFilter

# TODO: Make sure no one can edit/response/accept-response on an ended project
# TODO: Refactor this into a views module


class ProjectList(ListView):
    model = Project
    context_object_name = 'projects'
    template_name = 'projects/list.html'
    features_required = (features.projects,)
    status_filter = None

    def get_template_names(self):
        if self.request.is_ajax() and self.request.GET.get(
                'filter', '').strip() == 'yes':
            return 'projects/partials/filter_results.html'
        return self.template_name

    def get_context_data(self):
        user = self.request.user
        ctx = super(ProjectList, self).get_context_data()
        ctx['project_status_choices'] = StaffingRequest.STATUS

        ctx['projects'] = ProjectFilter(
            self.request.GET,
            request=self.request,
            queryset=ctx['projects']
        )

        if user.is_client:
            ctx['archived_projects'] = Project.objects.filter(is_archived=True)

        content_type = ContentType.objects.get_for_model(Project)

        unread = Event.objects.filter(Q(content_type=content_type,
                                        user=user))

        unread_events = {}
        for event in unread:
            events = unread_events.get(event.content_type.id, [])
            events.append(event)
            unread_events[event.content_type.id] = events

        ctx['unread_events'] = unread_events

        filters = {}
        ctx['filters'] = filters
        ctx['draft_requests_count'] = StaffingRequest.drafts.filter(
            created_by=self.request.user).count()
        ctx['active_nav_tab'] = 'projects'
        return ctx

    def get_queryset(self):
        user = self.request.user

        qs = self.model.objects.all()
        if user.is_vendor:
            q = Q(staffing_requests__is_public=True)
            q = q | Q(staffing_requests__vendors=user.vendor)
            v = Q(status=Project.DRAFT)
            v = v | Q(is_archived=True)
            qs = qs.filter(q).exclude(v)
        else:
            qs = qs.exclude(is_archived=True)

        return qs.distinct()
project_list = member_required(ProjectList.as_view())


class InviteUserToRequest(FormView):
    form_class = ProjectInviteForm
    template_name = 'projects/invite_to_project.html'
    success = False
    target_user = None
    proposed = None

    def get_template_names(self):
        if self.request.is_ajax():
            return 'projects/invite_to_project_modal.html'
        else:
            return self.template_name

    def get_success_url(self):
        if self.proposed:
            return self.proposed.get_absolute_url()
        elif self.target_user:
            return reverse('users:profile', args=(self.target_user.username,))
        else:
            return reverse('users:list')

    def get_context_data(self, form=None):
        context = super(InviteUserToRequest, self).get_context_data()
        context['staffing_projects'] = Project.objects.filter(
            staffing_requests__status=StaffingRequest.STAFFING)
        context['user_invite_form'] = form
        context['success'] = self.success
        return context

    def get_initial(self):
        initial = super(InviteUserToRequest, self).get_initial()
        initial['users'] = self.request.GET.getlist('users', [])
        return initial

    def get_form_kwargs(self):
        kwargs = super(InviteUserToRequest, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        staffing_request = form.cleaned_data['request']
        users = form.cleaned_data['users']
        message = form.cleaned_data['message']
        sender = self.request.user
        present = staffing_request.vendors.values_list('id', flat=True)
        vendors = Vendor.objects.filter(users=users).exclude(id__in=present)
        for vendor in vendors:
            RequestVendorRelationship\
                .objects.get_or_create(created_by=sender,
                                       request=staffing_request,
                                       vendor=vendor)
        tenant = connection.get_tenant()

        user_list = [user.id for user in users]

        request_info_task.delay(tenant_id=tenant.id, user_list=user_list,
                                message=message,
                                sender_id=sender.id,
                                sr_id=staffing_request.id)

        self.success = True
        if self.request.is_ajax() and not 'HTTP_X_PJAX' in self.request.META:
            return self.render_to_response(self.get_context_data(form))
        return super(InviteUserToRequest, self).form_valid(form)
invite_users = member_required(InviteUserToRequest.as_view())


# Client views
class CreateProject(BaseEditView):
    model_form = ProjectForm
    features_required = (features.projects,)

    def dispatch(self, *args, **kwargs):
        self.is_iframed = self.request.GET.get('iframed', '').strip() == 'yes'
        return super(CreateProject, self).dispatch(*args, **kwargs)

    def get_template_names(self):
        if self.is_iframed:
            if self.object:
                return ['projects/ajax_result.html']
            return ['projects/create_form.html']
        if self.request.is_ajax() and not 'HTTP_X_PJAX' in self.request.META:
            return ['projects/create_form_ajax.html']
        else:
            return ['projects/create.html']

    def get_success_url(self):
        return self.object.get_absolute_url()

    def get_form_kwargs(self):
        kwargs = super(CreateProject, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_initial_data(self):
        tomorrow = today() + timedelta(days=1)
        return {'start_date': tomorrow, 'owners': [self.request.user]}

    def pre_save(self, instance):
        instance.user = self.request.user
        instance.last_activity = self.request.user
        return instance

    def get_context_data(self, *args, **kwargs):
        context = super(CreateProject, self).get_context_data(*args, **kwargs)
        context['STATUS_DESCRIPTIONS'] = StaffingRequest.STATUS_DESCRIPTIONS
        context['object'] = self.object
        return context

    def form_valid(self, form):
        ret_val = super(CreateProject, self).form_valid(form)

        ajax_or_iframe = self.request.is_ajax() or self.is_iframed
        is_pjax = 'HTTP_X_PJAX' in self.request.META
        if ajax_or_iframe and not is_pjax:
            return self.render_to_response(self.get_context_data(
                form=form, success=True))
        else:
            return ret_val


class UpdateProject(UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'projects/create.html'
    context_object_name = 'project'
    features_required = (features.projects,)

    def post_save(self, instance):
        # todo send notification from here
        return instance

    def get_initial(self):
        initial = super(UpdateProject, self).get_initial()
        initial['owners'] = [self.request.user.id]
        return initial

    def get_form_kwargs(self):
        kwargs = super(UpdateProject, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_context_data(self, *args, **kwargs):
        context = super(UpdateProject, self).get_context_data(*args, **kwargs)
        context['STATUS_DESCRIPTIONS'] = StaffingRequest.STATUS_DESCRIPTIONS

apps/projects/templates/responses/proposed_resource_details.html
{% pjaxr_extends "base_template.html" "Site" %}
{% load projects %}
{% load crispy_forms_tags %}
{% load date_tags %}

{% block title %}{{ object.resource.get_name_display }} - {{ current_tenant.name }}{% endblock %}

{% block page_title %}<span id="page-title">Proposed resource </span>{% endblock %}

{% block left_nav_button %}
  <span id="left-nav-btn" class="pull-left">
    {% if previous_page %}{% endif %}
  </span>
{% endblock %}

{% block right_nav_button %}
  <span id="right-nav-btn" class="pull-right"></span>
{% endblock %}

{% block right_sidebar %}
  <div id="sidebar-right" class="sidebar sidebar-right"></div>
{% endblock %}

{% block notifications %}
  {% include 'partials/notifications.html' %}
{% endblock %}

{% block page %}
{% get_possible_forward_statuses object user as possible_statuses %}
  {% if user.username == 'jagmeet' %}
    <div class="container lifecycle">
      <ul class="nav nav-wizard">
        <li class="active">
          <a id='step-1' href="#"
              data-toggle="popover"
              data-trigger="click"
              data-html="true"
              data-placement="bottom"
              data-container="body"
              data-content="
              <div class='small popover-action-list'>
                <span class='list-group-item break-word'>
                  Responsible: <b>Matt <span class='text-muted'>matt@thismoment.com</span></b>
                </span>

                <span class='list-group-item break-word'>
                  <b>Resume: <a href='#'>download <i class='fa fa-file-pdf-o'></i></a></b>
                </span>

                <span class='list-group-item break-word'>
                  <small>Notify:</small> Owais Lone (Hiring Manager) <i class='fa fa-pencil'></i>
                </span>

                <span class='list-group-item break-word text-right'>
                  <a href='#step-2' class='next-action btn btn-primary btn-sm'>Done</a>
                </span>
              </div>
              "
            >
            <i class="fa fa-check-square-o"></i> Proposed <i class="fa fa-caret-down"></i>
          </a>
        </li>
        <li>
          <a id='step-2' href="#"
              data-toggle="popover"
              data-trigger="click"
              data-html="true"
              data-placement="bottom"
              data-container="body"
              data-content="
              <div class='small popover-action-list'>
                <span class='list-group-item break-word'>
                  Responsible: <b>Owais Lone (Hiring Manager)</b>
                </span>

                <span class='list-group-item break-word'>
                  <small>Notify:</small> Owais Lone (Hiring Manager)<i class='fa fa-pencil'></i>
                </span>

                <span class='list-group-item break-word text-right'>
                  <a href='#step-3' class='next-action btn btn-primary btn-sm'>Done</a>
                </span>
              </div>
              "
            >
            Shortlisted <i class="fa fa-caret-down hide"></i></a>
        </li>
        <li>
          <a id='step-3' href="#"
              data-toggle="popover"
              data-trigger="click"
              data-html="true"
              data-placement="bottom"
              data-container="body"
              data-content="
              <div class='small popover-action-list'>
                <span class='list-group-item break-word'>
                  Responsible: <b>Owais Lone (Hiring Manager)</b>
                </span>

                <span class='list-group-item break-word'>
                  <small>Notify:</small> Philip McNamara (Vendor Contact) <i class='fa fa-pencil'></i>
                </span>

                <span class='list-group-item break-word text-right'>
                  <a href='#step-4' class='next-action btn btn-primary btn-sm'>Done</a>
                </span>
              </div>
              "
              >
            Interview <i class="fa fa-caret-down hide"></i></a>
        </li>
        <li><a id='step-4' href="#"
              tab-index="0"
              data-toggle="popover"
              data-trigger="click"
              data-html="true"
              data-placement="bottom"
              data-container="body"
              data-content="
              <div class='small popover-action-list'>
                <span class='list-group-item break-word'>
                  Responsible: <b>Philip McNamara (Vendor Contact) & Owais Lone (Hiring Manager)</b>
                </span>

                <span class='list-group-item break-word'>
                  <form class='form-horizontal'>
                    <div class='form-group'>
                      <input class='form-control' placeholder='Start date'/>
                      <input class='form-control' placeholder='End date'/>
                      <input class='form-control' placeholder='Rate'/>
                      <input class='form-control' placeholder='Location'/>
                      <input class='form-control' placeholder='Allocation'/>
                    </div>
                  </form>
                </span>

                <span class='list-group-item break-word'>
                  <small>Notify:</small> Suzanne Jordan (Procurement) <i class='fa fa-pencil'></i>
                </span>

                <span class='list-group-item break-word text-right'>
                  <a href='#step-5' class='next-action btn btn-primary btn-sm'>Done</a>
                </span>
              </div>
              "
              >
              Business terms <i class="fa fa-caret-down hide"></i></a>
          </a>
        <li><a id='step-5' href="#"
              tab-index="0"
              data-toggle="popover"
              data-trigger="click"
              data-html="true"
              data-placement="bottom"
              data-container="body"
              data-content="
              <div class='small popover-action-list'>
                <span class='list-group-item break-word'>
                  Responsible: <b>Suzanne Jordan (Admin)</b>
                </span>


                <span class='list-group-item break-word'>
                  <b>SOW Template: <a href='#'>download <i class='fa fa-file-word-o'></i></a></b>
                </span>

                <span class='list-group-item break-word'>
                  <small>Notify:</small> Suzanne Jordan (Procurement) <i class='fa fa-pencil'></i>
                </span>

                <span class='list-group-item break-word text-right'>
                  <a href='#step-6' class='next-action btn btn-primary btn-sm'>Done</a>
                </span>
              </div>
              "
              >
              SOW <i class="fa fa-caret-down hide"></i></a>
        </li>
        <li><a id='step-6' href="#"
              tab-index="0"
              data-toggle="popover"
              data-trigger="click"
              data-html="true"
              data-placement="bottom"
              data-container="body"
              data-content="
              <div class='small popover-action-list'>
                <span class='list-group-item break-word'>
                  Responsible: <b>Suzanne Jordan (Admin)</b>
                </span>


                <span class='list-group-item break-word'>
                  <b>NDA Template: <a href='#'>download <i class='fa fa-file-word-o'></i></a></b>
                </span>

                <span class='list-group-item break-word'>
                  <small>Notify:</small> Suzanne Jordan (Procurement) <i class='fa fa-pencil'></i>
                </span>

                <span class='list-group-item break-word text-right'>
                  <a href='#step-7' class='next-action btn btn-primary btn-sm'>Done</a>
                </span>
              </div>
              "
              >
              NDA <i class="fa fa-caret-down hide"></i></a>
        </li>
        <li><a id='step-7' href="#"
              tab-index="0"
              data-toggle="popover"
              data-trigger="click"
              data-html="true"
              data-placement="bottom"
              data-container="body"
              data-content="
              <div class='small popover-action-list'>
                <span class='list-group-item break-word'>
                  Responsible: <b>Suzanne Jordan (Admin)</b>
                </span>


                <span class='list-group-item break-word'>
                  <b>Taining video: <a href='#'>download <i class='fa fa-file-video'></i></a></b>
                </span>

                <span class='list-group-item break-word'>
                  <small>Notify:</small> Suzanne Jordan (Procurement) <i class='fa fa-pencil'></i>
                </span>

                <span class='list-group-item break-word text-right'>
                  <a href='#step-8' class='anchor next-action btn btn-primary btn-sm'>Done</a>
                </span>
              </div>
              "
              >
              Training <i class="fa fa-caret-down hide"></i></a>
        </li>

        <li><a id='step-8' href="#">
          Complete</a>
        </li>
      </ul>
      <hr/>
    </div>
  {% endif %}

  <div id="page" class="container page">
    {% block content %}
      <ol class="breadcrumb custom">
        <li><a href="{% url 'projects:list' %}">Projects</a></li>
        <li><a href="{{ proposedresource.project.get_absolute_url }}">Project details</a></li>
        <li><a href="{{ proposedresource.request.get_absolute_url }}">Staffing details</a></li>
        <li class="active">Proposed resource</li>
      </ol>
      {% if q_status and perms.projects.add_proposedresource %}
        <div class="status-change-confirmation">
          {% for status in possible_statuses  %}
            {% ifequal q_status status.id|slugify %}
              <div class="alert alert-warning row">
                <div class="col-sm-8">
                  <i class="fa fa-exclamation-circle no-padding"></i>
                  Are you sure you want to change the status to {{ status }}
                </div>
                <div class="col-sm-4 text-right">
                  <a href="#"
                     class="{{ class }} proposed-status-btn"
                     data-action-url="{% url 'staffing:change_proposed_status' object.id %}"
                     data-status-id="{{ status.id }}"
                     data-staff-id="{{ object.id }}"
                     data-cost="{{ object.total_cost }}"
                     data-target=".proposed-status-btn-{{ object.id }}"
                     >
                  <button type="submit" class="btn btn-danger btn-xs">Yes</button>
                  </a>
                  <button type="submit" class="btn btn-default btn-xs cancel-btn" >No</button>
                </div>               
              </div>
            {% endifequal %}
          {% endfor %}
        </div>
        <br>
      {% endif %}
      <div class="panel panel-default relative">
        <div class="panel-body">
          {% include 'responses/proposed_staff_member.html' with show_details=True as_card=True project=object.project proposed_resource_object=object vendor=object.response.vendor person=object.resource %}
        </div>
      </div>
    {% endblock %}
  </div>
{% endblock %}

{% block js_foot %}
  <script>
    $('body').on('click', '.next-action', function(){
      $(this).parents().find('li.active').removeClass('active');
      var href = $(this).attr('href');
      var $step = $(href);
      if ($step.length > 0) {
        $(this).parents().find('[data-toggle="popover"]').popover('hide');
        $step.popover('show');
        $step.parent().addClass('active');
        $('.nav-wizard').find('.fa-caret-down').addClass('hide');
        $step.find('.fa-caret-down').removeClass('hide');
      }
    });
  </script>
{% endblock %}
{% block pjaxr_namespace %}Site.projects.proposed_resource_details{% endblock pjaxr_namespace %}

apps/projects/templates/responses/proposed_resourse_create.html
{% pjaxr_extends "base_template.html" "Site" %}
{% load crispy_forms_tags %}
{% block title %}
  {% if object.id %}
    Edit Proposed Resource
  {% else %}
    Propose A Resource
  {% endif %}
- {{ current_tenant }}{% endblock %}

{% block page_title %}<span id="page-title">
  {% if object.id %}
    Edit staff
  {% else %}
    Add project staff
  {% endif %}
</span>{% endblock %}

{% block left_nav_button %}
  <span id="left-nav-btn" class="pull-left">
    {% if previous_page %}
      <a class="navbar-brand btn" href="{{ previous_page }}"><i class="fa fa-chevron-left"></i></a>
    {% else %}
      <a class="navbar-brand btn" href="{{ project.get_absolute_url }}"><i class="fa fa-chevron-left"></i></a>
    {% endif %}
  </span>
{% endblock %}

{% block right_nav_button %}
  <span id="right-nav-btn" class="pull-right"></span>
{% endblock %}

{% block right_sidebar %}
  <div id="sidebar-right" class="sidebar sidebar-right"></div>
{% endblock %}

{% block notifications %}
  {% include 'partials/notifications.html' %}
{% endblock %}

{% block page %}
  <div id="page" class="container page">
    {% block content %}
      <ol class="breadcrumb custom">
        <li><a href="{% url 'projects:list' %}">Projects</a></li>
        <li><a href="{{ staffing_request.project.get_absolute_url }}">Project details</a></li>
        <li><a href="{{ staffing_request.get_absolute_url}}" class="active">Staffing request</a></li>
        <li class="active">{% if object.id %}Edit staff{% else %}Add project staff{% endif %}</li>
      </ol>
      <form id="add-staff-direct-form" class="form-mobile staffing-form form-horizontal" role="form" action=".?next={{ next_page }}" method="POST" data-rate-suggestions-url="{% url 'rates:suggestions' %}">
          {% csrf_token %}
         
          {% include 'forms/mobile_form.html' with form=form %}

          {% if features.financials.is_enabled %}
            {% include 'responses/proposed_rates.html' with form=form %}
          {% endif %}

          <div class="text-center form-actions">
          {% if object.id %}
            <a data-toggle="modal" data-target="#confirmRemoveProposedResourceModal" href="{% url 'staffing:remove_proposed_resource' object.id %}" class="btn btn-default">Remove</a>&nbsp;
          {% endif %}
            <button type="submit" class="btn btn-primary">{% if object.id %}Save{% else %}Add Resource{% endif %}</button>
          </div>
      </form>
      {% include 'users/invite_modal.html' %}
      {% include 'rates/create_modal.html' %}
    {% endblock %}

    <!-- Modal -->
    <div class="modal fade" id="confirmRemoveProposedResourceModal" tabindex="-1" role="dialog" aria-labelledby="confirmRemoveFromStaffModal" aria-hidden="true" data-keyboard="false" data-backdrop="static">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>
  </div>

{% endblock %}
{% block pjaxr_namespace %}Site.response_propose_resource{% endblock pjaxr_namespace %}

apps/projects/templates/responses/proposed_status_details.html
ok