apps/customers/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from .views import HomeView, CreateForAutocomplete, ProjectsStatus, MyProjectsStatus, VendorSearch


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^search/$', login_required(VendorSearch.as_view()), name='search'),
    url(r'^status/$', login_required(ProjectsStatus.as_view()), name='projects_status'),
    url(r'^mystatus/$', login_required(MyProjectsStatus.as_view()), name='my_projects_status'),
    url(r'^settings/', include('customers.settings_urls', namespace='client_settings')),
    url(r'^core/autocomplete/(?P<content_type_pk>\d+)/create/$',
        login_required(CreateForAutocomplete.as_view()), name='create_for_autocomplete'),
]

apps/roles/urls.py
from django.conf.urls import patterns, url

from roles import views
from med_social.decorators import admin_required

urlpatterns = [
    url(r'^$', admin_required(views.list_roles), name='list'),
    url(r'^create/$', admin_required(views.create_role), name='create'),
    url(r'^(?P<pk>\d+)/update/$', admin_required(views.update_role), name='edit'),
    url(r'^(?P<pk>\d+)/delete/$', admin_required(views.delete_role), name='delete'),
]

med_social/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.conf import settings

from allauth.account.views import LoginView
from djangosaml2.views import echo_attributes
from mailviews import previews
previews.autodiscover()

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from notifications import urls as notifications_urls
admin.autodiscover()

from users.forms import CustomLoginForm
from .views import WaitListView, InviteView, InviteApplyView, About
from .decorators import member_required, client_required
from .admin import site as admin_site

urlpatterns = [
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^emails/', include(previews.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    # We overrided some variables in allauth's original form implementation
    url(r'^accounts/login/$',
        LoginView.as_view(form_class=CustomLoginForm),
        name="account_login"),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^waitlist/$', login_required(WaitListView.as_view()), name='waitlist'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact_us.html'), name='contact_us'),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'^invite/$', member_required(InviteView.as_view()), name='invite'),
    url(r'^apply/@(?P<username>%s)/$' % settings.ACCOUNT_USERNAME_REGEX, InviteApplyView.as_view(), name='invite_link'),

    url(r'^api/', include('API.urls', namespace='api')),

    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^staffing/', include('projects.staffing_urls', namespace='staffing')),
    url(r'^availability/', include('availability.urls', namespace='availability')),
    url(r'^vendors/', include('vendors.urls', namespace='vendors')),
    url(r'^u/', include('users.setup_urls', namespace='user_setup')),
    url(r'^metrics/', include('reviews.metric_urls', namespace='metrics')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^notes/', include('notes.urls', namespace='notes')),
    url(r'^services/', include('services.urls.vendors', namespace='services')),
    url(r'^groups/', include('ACL.urls', namespace='groups')),
    url(r'^notifications/', include(notifications_urls)),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^rates/', include('rates.urls', namespace='rates')),
    url(r'^channels/', include('channels.urls', namespace='channels')),
    url(r'^suggest/', include('core.suggestions_urls', namespace='suggestions')),
    url(r'^a/', include('analytics.urls', namespace='analytics')),
    url(r'^locations/', include('locations.urls', namespace='locations')),
    url(r'^divisions/', include('divisions.urls', namespace='divisions')),
    url(r'^clients/', include('clients.urls', namespace='clients')),
    url(r'', include('customers.urls')),
    url(r'^activity/', include('activity.urls', namespace='activity')),
    url(r'^blog/', include('posts.urls', namespace='posts')),
    url(r'^payments/', include('djstripe.urls', namespace='djstripe')),
    url(r'^saml2/', include('djangosaml2.urls')),
    url(r'^test/', echo_attributes),
    url(r'^rfp/', include('lightrfp.urls')),
]

# Serve static files in development
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

admin.site.login = admin_site.login

# Usefull for testing prod environment locally without nginx
#urlpatterns += patterns('',
#   url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
#       'document_root': settings.STATIC_ROOT,
#   }),
#)

apps/roles/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse

from autoslug.fields import AutoSlugField
from autoslug.settings import slugify
from colorfield.fields import ColorField


class Role(models.Model):
    name = models.CharField(max_length=127)
    slug = AutoSlugField(populate_from='name', unique=True)
    color = ColorField(default='#f2f1f0')

    def __unicode__(self):
        return self.name

    @classmethod
    def can_create(self, user):
        return True

    @classmethod
    def create_for_autocomplete(cls, text, request):
        slug = slugify(text)
        item, created = cls.objects.get_or_create(slug=slug,
                                                  defaults={'name': text})
        return {'text': item.name, 'pk': item.pk}

    @classmethod
    def get_autocomplete_create_url(cls, extra_data=None):
        ctype = ContentType.objects.get_for_model(cls)
        return reverse('create_for_autocomplete', args=(ctype.id,))

apps/roles/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse

from med_social.decorators import client_required
from .models import Role


class ListRoles(ListView):
    model = Role
    template_name = 'roles/list.html'
    context_object_name = 'roles'
list_roles = client_required(ListRoles.as_view())


class CreateRole(CreateView):
    model = Role
    fields = '__all__'
    template_name = 'roles/create.html'
    context_object_name = 'role'

    def get_success_url(self):
        return reverse('client_settings:roles:list')
create_role = client_required(CreateRole.as_view())


class UpdateRole(UpdateView):
    model = Role
    fields = '__all__'
    template_name = 'roles/create.html'
    context_object_name = 'role'

    def get_success_url(self):
        return reverse('client_settings:roles:list')
update_role = client_required(UpdateRole.as_view())


class DeleteRole(DeleteView):
    model = Role
    context_object_name = 'role'

    def get_success_url(self):
        return reverse('client_settings:roles:list')
delete_role = client_required(DeleteRole.as_view())

apps/roles/templates/roles/card.html
<a href="{%url 'client_settings:roles:edit' role.id %}" class="field-group">
  <label>
    {{ role }}
  </label>
  <div class="field-value">
    <i class="fa fa-chevron-right text-muted"></i> 
  </div>
</a>

apps/roles/templates/roles/create.html
{% pjaxr_extends "base_template.html" "Site" %}
{% load crispy_forms_tags %}
{% block title %}{{ role|yesno:'Edit,New'}} role - {{ current_tenant }}{% endblock %}

{% block page_title %}<span id="page-title">{{ role|yesno:"Edit,New"}} Role</span>{% endblock %}

{% block left_nav_button %}
  <span id="left-nav-btn" class="pull-left">
    {% if previous_page %}
      <a class="navbar-brand btn" href="{{ previous_page }}"><i class="fa fa-chevron-left"></i></a>
    {% else %}
      <a class="navbar-brand btn" href="{% url 'client_settings:roles:list' %}"><i class="fa fa-chevron-left"></i></a>
    {% endif %}
  </span>
{% endblock %}

{% block right_nav_button %}
  <span id="right-nav-btn" class="pull-right"></span>
{% endblock %}

{% block right_sidebar %}
  <div id="sidebar-right" class="sidebar sidebar-right"></div>
{% endblock %}

{% block notifications %}
  {% include 'partials/notifications.html' %}
{% endblock %}

{% block page %}
  <div id="page" class="container page">
    {% block content %}
      <ol class="breadcrumb custom">
        <li><a href="{% url 'client_settings:home' %}">Settings</a></li>
        <li><a href="{% url 'client_settings:home' %}">Roles</a></li>
        <li class="active">{{ role|yesno:"Edit,New"}} role</li>
      </ol>

      <form id="role-form" class="form-mobile form-horizontal" role="form" action="{% if role %}{% url 'client_settings:roles:edit' role.id %}{% else %}{% url 'client_settings:roles:create' %}{% endif %}" method="POST">
        {% csrf_token %}
        {% include 'forms/mobile_form.html' with form=form submit_btn=False submit_btn_label='Save' form_title='Details' %}
        <div class="text-center form-actions">
          <button type="submit" class="btn btn-block btn-primary">{% if role %}Save{% else %}New role{% endif %}</button>
        </div>
     </form>
     
    {% endblock %}
  </div>
{% endblock %}
{% block pjaxr_namespace %}Site.roles.create{% endblock pjaxr_namespace %}

apps/roles/templates/roles/list.html
{% pjaxr_extends "base_template.html" "Site" %}
{% block title %}Roles - {{ current_tenant }}{% endblock %}

{% block page_title %}<span id='page-title'>Roles</span>{% endblock %}

{% block left_nav_button %}
  <span id="left-nav-btn" class='pull-left'>
  <a class="navbar-brand btn" href="{% url 'client_settings:home' %}"><i class="fa fa-chevron-left"></i></a></span>
{% endblock %}

{% block right_nav_button %}
  <span id="right-nav-btn" class="pull-right">
    <span class="navbar-brand">
      <a class="btn btn-xs btn-primary" href="{% url 'client_settings:roles:create' %}" class="btn btn-sm btn-primary"><span>new role</span></a>
    </span>
  </span>
{% endblock %}

{% block right_sidebar %}
  <div id="sidebar-right" class="sidebar sidebar-right">
    <div class="sidebar-heading clearfix">
      <a href="#" class="no-underline btn btn-lg">
        <i class="fa fa-chevron-right"></i>
      </a>
    </div>
  </div>
{% endblock %}

{% block notifications %}
  {% include 'partials/notifications.html' %}
{% endblock %}

{% block page %}
  <div id="page" class="container page">
    {% block content %}
      <ol class="breadcrumb custom">
        <li><a href="{% url 'client_settings:home' %}">Settings</a></li>
        <li class="active">Roles</li>
      </ol>

    {% if roles %}
      <div class="page-top-band">
          <div class="col-xs-12 text-center">
            <h6>all roles ({{ roles.count }})</h6>
          </div>
      </div>
      <div class="panel panel-default role-card">
        <div class="panel-body">
          {% for role in roles %}
            {% include 'roles/card.html' with role=role %}
          {% endfor %}
        </div>
      </div>
    {% endif %}
    {% endblock %}
   </div>
{% endblock %}
{% block pjaxr_namespace %}Site.roles.list{% endblock pjaxr_namespace %}