apps/projects/urls.py
from django.conf.urls import patterns, url, include

from med_social.decorators import (member_required, vendor_required, client_required)

from .views import (CreateProject, UpdateProject, ProjectDetails,
                    ProjectBudget, SendProposalView, budget_details,project_list,
                    my_project_list, staffing_confirmation, add_user_to_project,
                    share_project, change_proposed_status, invite_users)


urlpatterns = patterns('projects.views',
    url(r'^$', project_list, name='list'),
    url(r'^my/$', my_project_list, name='my_list'),
    url(r'^create/$', member_required(CreateProject.as_view()), name='create'),
    url(r'^(?P<pk>\d+)/$', member_required(ProjectDetails.as_view()),
        name='detail'),
    url(r'^(?P<pk>\d+)/users/add/$', add_user_to_project,
        name='add_user'),
    url(r'^(?P<pk>\d+)/budget/$', member_required(ProjectBudget.as_view()),
        name='budget_label'),
    url(r'^(?P<pk>\d+)/budget/details/$', budget_details,
        name='budget_details'),
    url(r'^(?P<pk>\d+)/edit/$', UpdateProject.as_view(), name='edit'),
    #url(r'^(?P<pk>\d+)/status/edit/$', 'update_project_status', name='edit_status'),
    url(r'^(?P<project_pk>\d+)/proposed/(?P<pk>\d+)/status/$',
        change_proposed_status,
        name='change_proposed_status'
    ),
    url('responses/send_proposal/(?P<pk>\d+)/$',
        vendor_required(SendProposalView.as_view()),
        name='send_proposal'
    ),
    url('users/invite/$', invite_users, name='invite_users'),
    url('status/', include('projects.status_urls', namespace='status')),
    url(r'^confirm/(?P<sr_pk>\d+)/(?P<answer>\d+)/$',
        vendor_required(staffing_confirmation),
        name='staffing_confirmation'),
    url(r'^(?P<project_pk>\d+)/team/$',
        client_required(share_project),
        name='share_project'),
)

apps/users/urls.py
from django.conf.urls import patterns, url

from med_social.decorators import (member_required,
                                   admin_required)
from . import views

UUID = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

urlpatterns = [
    url(r'^$', admin_required(views.UsersList.as_view()), name='list'),
    url(r'^notifications/mark_read/$', views.mark_notifs_read, name='mark_notifs_read'),
    url(r'^notifications/all/$', views.all_notifications, name='all_notifications'),
    url(r'^notifications/read/$', views.read_notifications, name='read_notifications'),
    url(r'^notifications/unread/$', views.unread_notifications, name='unread_notifications'),
    url(r'^join/(?P<uuid>{})'.format(UUID), views.UserDirectJoinView.as_view(), name='direct_join'),
    url(r'^signups/$', views.signups, name='signups'),
    url(r'^signups/(?P<pk>\d+)/approve/$', views.signup_approve, name='signup_approve'),
    url(r'^signups/(?P<pk>\d+)/reject/$', views.signup_delete, name='signup_delete'),
    url(r'^invite/$', views.user_invite_view, name='invite'),
    url(r'^register/$', views.user_register_view, name='register'),
    url(r'^register/confirm/(?P<uuid>{})'.format(UUID), views.user_confirm_view, name='confirm_register'),
    url(r'^search/$', member_required(views.user_search), name='search'),
    url(r'^invite/(?P<pk>\d+)/$', views.user_direct_invite_view, name='direct_invite'),
    url(r'^invite/resend/(?P<pk>\d+)/$', views.user_resend_invite_view, name='resend_invite'),
    url(r'^(?P<pk>\d+)/delete/$', admin_required(views.UserDelete.as_view()), name='delete'),
    url(r'^(?P<pk>\d+)/permissions/$', views.UserPermissionsUpdate.as_view(), name='edit_permission'),
    url(r'^(?P<pk>\d+)/$', member_required(views.ProfileByID.as_view()), name='profile_by_id'),
    url(r'^(?P<username>[\w+.-]+)/$', member_required(views.ProfileDetails.as_view()), name='profile'),
    url(r'^(?P<username>[\w+.-]+)/modal/$', member_required(views.ProfileModalDetails.as_view()), name='profile_modal'),
    url(r'^(?P<username>[\w+.-]+)/allocation/add/$', views.add_allocation, name='add_allocation'),
    url(r'^(?P<username>[\w+.-]+)/allocation/(?P<pk>\d+)/edit/$', views.edit_allocation, name='edit_allocation'),
    url(r'^(?P<username>[\w+.-]+)/edit/$', views.profile_edit_view, name='edit_profile'),
    url(r'^password/reset/$', views.password_reset_view, name='password_reset'),
    url(r'^uploads/avatar/(?P<userid>\d+)/$', views.upload_avatar, name='upload_avatar'),
    url(r'^@(?P<username>[\w+-]+)/settings/notifications/$', views.settings_notifications, name='settings_notifications'),
]

med_social/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.conf import settings

from allauth.account.views import LoginView
from djangosaml2.views import echo_attributes
from mailviews import previews
previews.autodiscover()

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from notifications import urls as notifications_urls
admin.autodiscover()

from users.forms import CustomLoginForm
from .views import WaitListView, InviteView, InviteApplyView, About
from .decorators import member_required, client_required
from .admin import site as admin_site

urlpatterns = [
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^emails/', include(previews.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    # We overrided some variables in allauth's original form implementation
    url(r'^accounts/login/$',
        LoginView.as_view(form_class=CustomLoginForm),
        name="account_login"),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^waitlist/$', login_required(WaitListView.as_view()), name='waitlist'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact_us.html'), name='contact_us'),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'^invite/$', member_required(InviteView.as_view()), name='invite'),
    url(r'^apply/@(?P<username>%s)/$' % settings.ACCOUNT_USERNAME_REGEX, InviteApplyView.as_view(), name='invite_link'),

    url(r'^api/', include('API.urls', namespace='api')),

    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^staffing/', include('projects.staffing_urls', namespace='staffing')),
    url(r'^availability/', include('availability.urls', namespace='availability')),
    url(r'^vendors/', include('vendors.urls', namespace='vendors')),
    url(r'^u/', include('users.setup_urls', namespace='user_setup')),
    url(r'^metrics/', include('reviews.metric_urls', namespace='metrics')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^notes/', include('notes.urls', namespace='notes')),
    url(r'^services/', include('services.urls.vendors', namespace='services')),
    url(r'^groups/', include('ACL.urls', namespace='groups')),
    url(r'^notifications/', include(notifications_urls)),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^rates/', include('rates.urls', namespace='rates')),
    url(r'^channels/', include('channels.urls', namespace='channels')),
    url(r'^suggest/', include('core.suggestions_urls', namespace='suggestions')),
    url(r'^a/', include('analytics.urls', namespace='analytics')),
    url(r'^locations/', include('locations.urls', namespace='locations')),
    url(r'^divisions/', include('divisions.urls', namespace='divisions')),
    url(r'^clients/', include('clients.urls', namespace='clients')),
    url(r'', include('customers.urls')),
    url(r'^activity/', include('activity.urls', namespace='activity')),
    url(r'^blog/', include('posts.urls', namespace='posts')),
    url(r'^payments/', include('djstripe.urls', namespace='djstripe')),
    url(r'^saml2/', include('djangosaml2.urls')),
    url(r'^test/', echo_attributes),
    url(r'^rfp/', include('lightrfp.urls')),
]

# Serve static files in development
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

admin.site.login = admin_site.login

# Usefull for testing prod environment locally without nginx
#urlpatterns += patterns('',
#   url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
#       'document_root': settings.STATIC_ROOT,
#   }),
#)

apps/projects/templates/projects/partials/budget.html
{% load projects %}
{% load avatar_tags %}
{% load humanize %}

{% if perms.rates.view %}
  {% if cost %}
    <a href="{% url 'projects:budget_details' project.pk %}" class="btn btn-o btn-xs btn-v {% if user.is_client %}btn-{% get_budget_class cost budget %}{% else %}btn-secondary{% endif %}" data-toggle="modal" data-target="#genericModal">
      {% include 'rates/lock.html' %}&nbsp;
      <span><i class="fa fa-dollar"></i> </span>
      {{ cost|intcomma }}
      <small class="text-muted br"> {% if user.is_client %}estimated cost{% else %}total earned{% endif %} &nbsp;&nbsp;<i class="fa fa-angle-right"></i></small>
    </a>
  {% endif %}
{% endif %}

apps/projects/templates/projects/partials/filter_results.html
{% if projects %}
  {% for project in projects %}
    {% include 'projects/card.html' with project=project %}
  {% endfor %}
  <div class="block-cover text-center hide"></div>
{% else %}
  <div class="panel panel-default">
    <div class="panel-body">
      <br/>
        <div class="text-muted">No related projects.</div>
      <br/>
    </div>
  </div>
{% endif %}

apps/projects/templates/projects/partials/invite_to_project_form.html
{% load crispy_forms_tags %}
<div>
  {% if success %}
  <div class="success-result text-center">
    <h4><i class="fa fa-check-circle"></i> Message with link to the staffing request sent</h4>
  </div>
  {% endif %}
  <div class="form-horizontal {% if success %}hide{% endif %}">
    {% csrf_token %}
    {{ user_invite_form|crispy }}
  </div>
  <div class="block-cover hide"></div>
</div>

apps/projects/templates/projects/partials/proposed_edit_form.html
<form id="proposed-edit-form" class="form-mobile form-horizontal" role="form" action="{% url 'staffing:edit_proposed' proposed.id %}" method="POST" enctype="multipart/form-data" data-ajax-form data-parsley-validate>
  {% csrf_token %}
  <div class="modal-header">
    <div class="row">
      <div class="col-xs-12 text-right">
        <a href="#" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times text-muted"></i></a>
      </div>
    </div>
  </div>

  <div class="modal-body ">
    {% if object.updated %}
    	<div class="text-center result-item" data-pk="{{ object.pk }}" data-kind="project" data-text="{{ object.title }}">
		  <h2>
		    <i class="fa fa-check-circle text-muted"></i> Updated!
		  </h2>
		</div>

    {% else %}
      {% include 'forms/naked_form.html' with form=form %}
    {% endif %}
  </div>

  <div class="modal-footer">
  	{% if object.updated %}
  		<a href="#" data-dismiss="modal" class="btn btn-primary">OK</a>
  	{% else %}
      <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	    <button type="submit" class="btn btn-primary">Save</button>
  	{% endif %}
  </div>
</form>

apps/projects/templates/projects/partials/share_project_form.html
<form id="share-project-form" class="form-mobile form-horizontal" role="form" action="{% url 'projects:share_project' project.id %}" method="POST" enctype="multipart/form-data" data-ajax-form data-parsley-validate>
  {% csrf_token %}
  <div class="modal-header">
    <div class="row">
       <div class="col-xs-3 modal-action-left">
      </div>
      <div class="col-xs-6">
        <h4 class="modal-title text-center">Share project</h4>
      </div>
      <div class="col-xs-3 modal-action-right">
        <a href="#" class="btn" data-dismiss="modal"><i class="fa fa-times"></i></a>
      </div>
    </div>
  </div>

  <div class="modal-body ">
      {% include 'forms/naked_form.html' with form=form form_heading=None %}
  </div>

  <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>

apps/projects/templates/projects/partials/staffed_list.html
{% load projects %}
{% load utils %}

{% for proposed in project.sorted_proposals.all %}
  {% if proposed.is_staffed %}
    {% if user.is_client %}
      {% include 'projects/partials/staffed_user.html'%}
    {% elif proposed.resource.vendor == user.vendor %}
      {% include 'projects/partials/staffed_user.html'%}
    {% endif %}
  {% endif %}
{% empty %}
  {% if not project|can_staff_resources:user %}
  <li>
    <p class="small text-muted">No accepted or staffed user</p>
  </li>
  {% endif %}
{% endfor %}

{% if project|can_staff_resources:user %}
    <li class="media {% if proposed.end_date < proposed.project.end_date %}disabled-user{% endif %}">
      <div class="img-circle pull-left anchor text-center">
        <a href="{% url 'projects:add_user' project.id %}" data-toggle="modal" data-target="#genericModal"  data-modal-is-remote="true" class="new-user">
          <i class="fa fa-plus"></i>
        </a>
      </div>
      <div class="media-body">
        <h5 class="media-heading">Add staff</h5>
        <div class="media-description">&nbsp;</div>
      </div>
    </li>
{% endif %}

apps/projects/templates/projects/partials/staffed_user.html
{% load projects %}
{% load utils %}

<li class="media {% if proposed.end_date < proposed.project.end_date %}disabled-user{% endif %}">
  <div class="img-circle pull-left anchor text-center" href="{% url 'users:profile_modal' proposed.resource.username %}" data-toggle="modal" data-target="#userModal" style="background: {{ proposed.role.color|default:'#EEEEEE' }};border-color: {{ proposed.role.color|default:'#EEEEEE' }};color: {{ role.color|reverse_color }}">
    {% include 'partials/avatar_initials.html' with object=proposed.resource size=35 title=proposed.get_short_title %}
  </div>

  <div class="media-body">
    <h5 class="media-heading">
      {% if proposed.role.name %}
        <span class="dropdown">
          <span class="dropdown-toggle anchor" type="button" id="dropdownMenuProposed-{{proposed.id}}" data-toggle="dropdown" aria-expanded="true">
            <span>{{ proposed.resource.get_name_display|truncatechars:15 }}&nbsp;&nbsp;<i class="text-muted fa fa-caret-down"></i>
            </span>
          </span>
          <ul class="dropdown-menu dropdown-menu-right text-center anchor" role="menu" aria-labelledby="dropdownMenuProposed-{{proposed.id}}">
            <li role="presentation">
              <a role="menuitem" tabindex="-1" class="text-right " href="{% url 'staffing:edit_proposed' proposed.id %}" data-toggle="modal" data-target="#genericModal">edit</a>
            </li>
            <li>
              <a type='submit' class="propose-delete-btn text-right " data-url="{% url 'staffing:delete_proposed_resource' proposed.id %}" data-pk="{{proposed.id}}">unstaff</a>
            </li>
          </ul>
        </span>
      {% else %}
        {{ proposed.resource.get_name_display|truncatechars:15 }}
      {% endif %}
    </h5>
    <div class="media-description">
      {% if proposed.role.name %}
        {{ proposed.role.name }}
      {% else %}
        <span class="role empty">&nbsp;</span>
      {% endif %}
    </div>
  </div>
</li>