apps/rates/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
    url(r'^$', views.rate_list, name='list'),
    url(r'^(?P<pk>\d+)/$', views.rate_as_field, name='as_field'),
    url(r'^suggestions/$', views.suggestions, name='suggestions'),
    url(r'^create/$', views.create_rate, name='create'),
    #url(r'^user_rate/(?P<username>[\w\s@+.-]+)/$', views.edit_user_rate, name='edit_user_rate'),
    url(r'^(?P<pk>\d+)/edit/$', views.edit_rate, name='edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete_rate, name='delete'),
]

apps/reviews/urls.py
from django.conf.urls import patterns, url

# namespace

UUID = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

urlpatterns = patterns('reviews.views',
    url(r'^(?P<content_type_pk>\d+)/(?P<object_pk>\d+)/review/$', 'review_object', name='add'),
    url(r'^(?P<review_pk>\d+)/$', 'review_details', name='detail'),
    url(r'^(?P<content_type_pk>\d+)/(?P<object_pk>\d+)/$', 'review_list', name='list'),
    url(r'^(?P<content_type_pk>\d+)/(?P<object_pk>\d+)/$', 'review_list', name='list'),
    url(r'^public/create/(?P<uuid>{})'.format(UUID), 'public_review',
        name='public_review'),
    url(r'^(?P<content_type_pk>\d+)/(?P<object_pk>\d+)/review_token/$',
        'create_review_token', name='create_review_token'),
)

med_social/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.conf import settings

from allauth.account.views import LoginView
from djangosaml2.views import echo_attributes
from mailviews import previews
previews.autodiscover()

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from notifications import urls as notifications_urls
admin.autodiscover()

from users.forms import CustomLoginForm
from .views import WaitListView, InviteView, InviteApplyView, About
from .decorators import member_required, client_required
from .admin import site as admin_site

urlpatterns = [
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^emails/', include(previews.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    # We overrided some variables in allauth's original form implementation
    url(r'^accounts/login/$',
        LoginView.as_view(form_class=CustomLoginForm),
        name="account_login"),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^waitlist/$', login_required(WaitListView.as_view()), name='waitlist'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact_us.html'), name='contact_us'),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'^invite/$', member_required(InviteView.as_view()), name='invite'),
    url(r'^apply/@(?P<username>%s)/$' % settings.ACCOUNT_USERNAME_REGEX, InviteApplyView.as_view(), name='invite_link'),

    url(r'^api/', include('API.urls', namespace='api')),

    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^staffing/', include('projects.staffing_urls', namespace='staffing')),
    url(r'^availability/', include('availability.urls', namespace='availability')),
    url(r'^vendors/', include('vendors.urls', namespace='vendors')),
    url(r'^u/', include('users.setup_urls', namespace='user_setup')),
    url(r'^metrics/', include('reviews.metric_urls', namespace='metrics')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^notes/', include('notes.urls', namespace='notes')),
    url(r'^services/', include('services.urls.vendors', namespace='services')),
    url(r'^groups/', include('ACL.urls', namespace='groups')),
    url(r'^notifications/', include(notifications_urls)),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^rates/', include('rates.urls', namespace='rates')),
    url(r'^channels/', include('channels.urls', namespace='channels')),
    url(r'^suggest/', include('core.suggestions_urls', namespace='suggestions')),
    url(r'^a/', include('analytics.urls', namespace='analytics')),
    url(r'^locations/', include('locations.urls', namespace='locations')),
    url(r'^divisions/', include('divisions.urls', namespace='divisions')),
    url(r'^clients/', include('clients.urls', namespace='clients')),
    url(r'', include('customers.urls')),
    url(r'^activity/', include('activity.urls', namespace='activity')),
    url(r'^blog/', include('posts.urls', namespace='posts')),
    url(r'^payments/', include('djstripe.urls', namespace='djstripe')),
    url(r'^saml2/', include('djangosaml2.urls')),
    url(r'^test/', echo_attributes),
    url(r'^rfp/', include('lightrfp.urls')),
]

# Serve static files in development
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

admin.site.login = admin_site.login

# Usefull for testing prod environment locally without nginx
#urlpatterns += patterns('',
#   url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
#       'document_root': settings.STATIC_ROOT,
#   }),
#)

apps/reviews/models.py
from datetime import timedelta

from django.db import models, connection
from django.db.models import Sum, Avg
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.dispatch import receiver
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import post_init, post_save
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django_extensions.db.fields import UUIDField
from django.utils.timezone import now

from filtered_contenttypes.fields import FilteredGenericForeignKey

from vlkjsonfield.fields import VLKJSONField
from autoslug.fields import AutoSlugField
from model_utils.managers import QueryManager

from med_social.utils import humanized_datetime, send_notification_mail
from med_social.utils import get_score_level
from med_social.tasks import send_all_notification_task
from notifications.signals import notify

from .fields import base as metric_fields


def _get_default_metric_data():
    return metric_fields.BaseField.get_metric_data()


class Metric(models.Model):
    '''Facilitates custom metrics for reviews. Each metric can contain a
    score of 1-5 and have custom labels'''
    _supported_models = set([])

    SOURCE_AUTO = 1
    SOURCE_IMPORT = 2
    SOURCE_CLIENT = 3
    SOURCE_VENDOR = 4

    SOURCE_CHOICES = (
        (SOURCE_AUTO, 'Calculated by Proven',),
        # (SOURCE_IMPORT, 'Imported from another data source',),
        (SOURCE_CLIENT, 'Manually entered by client',),
        (SOURCE_VENDOR, 'Manually entered by vendor',),
    )
    DEFAULT_FIELD_CLASS = metric_fields.RatingField

    FIELD_CLASSES = {F.ID: F for F in metric_fields.FIELDS}
    FIELD_KIND_CHOICES = tuple([(F.ID, F.name,) for F in metric_fields.FIELDS])

    PERMISSIONS = (
        ('add_metric', 'Can add metric', Permission.CLIENT, True),
        ('view_metric', 'Can view metric', Permission.CLIENT, False)
    )

    name = models.CharField(_('metric name'), max_length=127)
    slug = AutoSlugField(populate_from='name', unique_with=['content_type'])
    help_text = models.TextField(_('help text'), default='', blank=True)
    weight = models.PositiveSmallIntegerField(default=0)
    kind = models.CharField(
        max_length=127,
        default=metric_fields.RatingField.ID, choices=FIELD_KIND_CHOICES)
    metric_data = VLKJSONField(
        default=_get_default_metric_data)
    source = models.PositiveSmallIntegerField(default=SOURCE_CLIENT,
                                              choices=SOURCE_CHOICES)
    is_deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(ContentType, related_name='metrics')

    objects = QueryManager(is_deleted=False)
    deleted_objects = QueryManager(is_deleted=True)
    all_objects = models.Manager()

    class Meta:
        ordering = ('-weight', 'id',)
        unique_together = (('content_type', 'slug',),)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id and not self.weight:
            weight = 100.0 - (Metric.objects.all().aggregate(
                Sum('weight')).get('weight__sum') or 0)
            if weight >= 0:
                self.weight = weight
        return super(Metric, self).save(*args, **kwargs)

    @classmethod
    def is_weight_sum_ok(klass, content_type):
        """ Tests if the given set of metrics has weight == 100 """
        queryset = Metric.objects.filter(content_type=content_type).all()
        return queryset.aggregate(Sum('weight')).get('weight__sum') == 100

    @property
    def is_enabled(self):
        return not(self.is_deleted and self.weight == 0)

    @property
    def field(self):
        if not hasattr(self, '__field__'):
            self.__field__ = self.FIELD_CLASSES[self.kind](self)
        return self.__field__

    @property
    def as_field_name(self):
        return self.name.lower().replace(' ', '')

    @classmethod
    def get_supported_models(self):
        return self._supported_models

    def get_display_choices(self):
        choices = [self.field.as_form_choice(label)
                   for label in self.metric_data['labels'].items()]
        return sorted(choices)

    def get_score_display(self, score):
        return self.field.get_score_display(score)

    def set_labels_from_kind(self):
        self.labels = self.field.labels

    def calculate_auto_score(self, value):
        return self.field.calculate_auto_score(value, self.metric_data['labels'])

    def clean(self):
        if not self.content_type_id:
            # If content-type has not been attached yet, skip the cleaning
            # it will be attched in future for sure as it is required
            return

        claimed = self.__class__.objects.filter(
            content_type=self.content_type
        ).exclude(id=self.id).aggregate(
            models.Sum('weight'))['weight__sum'] or 0

        available = 100 - claimed
        if self.weight and self.weight > available:
            raise ValidationError('Weight cannot be more than {}% as other'
                                  ' metrics collectively weigh {}%.'
                                  .format(available, claimed))

    def clean_metrics(self):
        if self.field:
            labels = self.metric_data.get('labels', {})
            for K, V in labels.items():
                labels[K] = self.field.clean(V)
            self.metric_data['labels'] = labels


class Review(models.Model):
    '''Review of a vendor by a client resource'''

    PERMISSIONS = (
        ('add_review', 'Can add review', Permission.CLIENT, False),
        ('view_review', 'Can view review', Permission.ALL, False)
    )
    content_type = models.ForeignKey(ContentType, related_name='reviews')
    object_id = models.PositiveIntegerField()
    content_object = FilteredGenericForeignKey('content_type', 'object_id')

    metrics = models.ManyToManyField(Metric, through='MetricReview')
    remarks = models.TextField(_('remarks'), default='', blank=True)
    score = models.DecimalField(blank=True, null=True, max_digits=2,
                                decimal_places=1)
    posted_by = models.ForeignKey('users.User', related_name='reviews_submitted',
                                  null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    anonymous = models.BooleanField(default=False)
    vendor_viewable = models.BooleanField(default=False)

    token = models.ForeignKey('ReviewToken', related_name='review',
                              null=True, blank=True)

    class Meta:
        get_latest_by = 'created'
        ordering = ('-created',)

    def __unicode__(self):
        if len(self.remarks) > 30:
            return '"{}..."'.format(self.remarks[:30].capitalize())
        return '"{}"'.format(self.remarks.capitalize())

    def save(self, *args, **kwargs):
        self.score = self.calculate_score()
        ret_val = super(Review, self).save(*args, **kwargs)
        if self.content_object:
            self.content_object.__Reviews__denorm_reviews__()
        return ret_val

    def delete(self, *args, **kwargs):
        content_object = self.content_object
        super(Review, self).delete(*args, **kwargs)
        if content_object:
            content_object.__Reviews__denorm_reviews__()

    def natural_created_date(self):
        return humanized_datetime(self.created)

    def calculate_score(self):
        score_sum = 0.0
        weight_sum = 0.0
        count = 0
        for metricreview in self.review_metrics.all():
            count += 1
            weight = metricreview.metric.weight
            score = float(metricreview.score)
            score_sum += (score * weight)
            weight_sum += weight
        if not score_sum or not weight_sum:
            return None
        return float('{:.1f}'.format(score_sum / weight_sum))

    def get_score_level(self):
        return get_score_level(self.score)

    def get_score_color(self):
        if not self.score:
            return '#D7D7D7'
        if self.score <= 2:
            return '#FF5600'
        elif self.score <= 3.5:
            return '#FFAD82'
        elif self.score <= 4:
            return '#80EE49'
        elif self.score <= 5:
            return '#3DBA3F'

    def get_notification_receivers(self):
        if hasattr(self.content_object, 'get_notification_receivers'):
            return self.content_object.get_notification_receivers()
        else:
            return []

    def get_absolute_url(self):
        return reverse('reviews:detail', args=(self.id,))

    def score_update(self):
        from vendors.models import Score
        score_obj, _ = Score.objects.get_or_create(vendor=self.content_object,
                                                   kind=Score.KIND_REVIEW)
        reviews = Review.objects\
            .filter(content_object=self.content_object)
        review_score = reviews.aggregate(Avg('score'))['score__avg']
        review_count = reviews.count()
        if not review_score:
            review_score = 0
        score = review_score + (review_score * review_count)
        if score:
            score_obj.score = score
        self.content_object.save()
        score_obj.save()


class MetricReview(models.Model):
    '''Through table for Metric-Review relationship. Also stores score given
    to the particular metric'''
    SCORE_1 = 1
    SCORE_2 = 2
    SCORE_3 = 3
    SCORE_4 = 4
    SCORE_5 = 5
    SCORE_CHOICES = (
        (SCORE_1, '1',),
        (SCORE_2, '2',),
        (SCORE_3, '3',),
        (SCORE_4, '4',),
        (SCORE_5, '5',),
    )
    review = models.ForeignKey(Review, related_name='review_metrics')

apps/reviews/templates/reviews/as-card.html
{% load avatar_tags %}
{% load review_tags %}
{% load utils %}
{% url 'reviews:detail' review.id as review_url %}
<div class="panel panel-default">
  <div class="panel-heading flat"></div>
  <div class="panel-body" href="{% url 'reviews:detail' review.id %}" class="review-card review-field">
      <blockquote>
        <p><i><a href="{{ review_url }}" class="no-link-style">{{ review.remarks }}</a></i></p>
      </blockquote>

      <div class="score-value score-font-size " >
                Rating: <span class="text-{% get_review_class vendor.avg_score %}">{% rating_stars vendor.avg_score %}</span> <h1>{{vendor.avg_score}}</h1>
      </div> 

      {% if review.anonymous %}
            <span>Someone at {{ review.posted_by.get_company_display }}<cite class="timestamp"> - {{ review.natural_created_date }}</cite></span>
          {% else %}
            <a href="{{ review.posted_by.get_profile_modal_url }}" class="no-link-style" data-toggle="modal" data-target="#userModal">
              <img src="{% avatar_url review.posted_by 25 %}" class="avatar avatar-25 img-circle"/>
              {{ review.posted_by }} 
            </a>
      {% endif %}
  </div>
</div>

apps/reviews/templates/reviews/as_field.html
{% load avatar_tags %}
{% load review_tags %}
{% load utils %}
{% url 'reviews:detail' review.id as review_url %}
<div class="panel panel-rating-{% get_review_color_class review.score %} panel-hint panel-review panel-card">
  <div class="panel-body" href="{% url 'reviews:detail' review.id %}" class="review-card review-field">
    <div class="media">
      {% if not review.anonymous %}
      <a href="{{ review.posted_by.get_profile_modal_url }}" class="pull-left" data-toggle="modal" data-target="#userModal">
        {% include 'partials/avatar_initials.html' with object=review.posted_by size=35 title=review.posted_by %}
      </a>
      {% endif %}

      <div class="media-body">
        <h5 class="media-heading">
          <div class="row">
            <div class="col-xs-8">
            {% if review.anonymous %}
              <b>Someone at {{ review.posted_by.get_company_display }}</b>
            {% else %}
              {% if review.token %}
                <b>{{ review.token.email }}</b>
              {% else %}
              <a href="{{ review.posted_by.get_profile_modal_url }}" class="no-link-style" data-toggle="modal" data-target="#userModal">
                <b>{{ review.posted_by }}</b>
              </a>
              {% endif %}
            {% endif %}
            </div>
            <div class="col-xs-4 text-right">
              <div class="score-value rating-stars small star_{% rating_stars_color review.score %}">{% rating_stars review.score %}</div>
              <div class="text-right text-{% get_review_class review.score %} small">
                <b>{{ review.score|default:"N/A"}}</b>{% if review.score %}<small>/5</small>{% endif %}
              </div>
            </div>
          </div>
        </h5>
      </div>
    </div>
    <p class="remarks description">
      {{ review.remarks }}<br>

      {% if not review_details %}
        <a href="{{ review_url }}" class="btn-link small no-underline">view more...</a>
      {% endif %}
      
    </p>
    <p class="small timestamp text-muted text-right">{{ review.natural_created_date }}</p>
  </div>
</div>

apps/reviews/templates/reviews/breakdown.html
{% load review_tags %}
<h6 class="section-title text-uppercase">score breakdown</h6>
{% for metric in review.review_metrics.all %}
  {% if metric.metric %}
    <div class="panel panel-rating-{% get_review_color_class metric.score %} panel-hint panel-card">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-10">
            {{ metric.metric.name }}
          </div>
          <div class="col-xs-2 text-right">
            
            <span class="small">
              <b class="text-semi-dark">{{ metric.score}}</b><small class="text-muted">/5</small>
            </span>
            
          </div>
        </div>
      </div>
      <div class="panel-body">
        <p><small>{{ metric.metric.help_text}}</small></p>
        {{ metric.get_metric_score_display }}
      </div>
    </div>
  {% endif %}
{% endfor %}

apps/reviews/templates/reviews/card.html
{% load avatar_tags %}
{% load review_tags %}

<div class="panel panel-rating-{% get_review_color_class review.score %} panel-hint  panel-card review-card">
  <div class="panel-body">
    <div class="field-group">
      <label>
        {% if review.user %}
          {% include 'partials/avatar_initials.html' with object=review.user size=25 %}
          <span>{{ review.user.get_name_display }}</span>
        {% else %}
          <span>{{ review.response.vendor}}</span>
        {% endif %}
      </label>
      <div class="field-value">
        &nbsp;{% include 'reviews/partials/as_label.html' with score=review.score %}
      </div>
    </div>

    <div class="field-group multi-line">
      <div class="field-value">
        {{ review.remarks }}
      </div>
    </div>

    {% for metric in review.review_metrics.all %}
      {% if metric.metric.is_enabled %}
      <div class="field-group">
        <label>{{ metric.metric.name }}</label>
        <div class="field-value">
          {{ metric.get_metric_score_display }}
        </div>
      </div>
      {% endif %}
    {% endfor %}
  </div>
</div>

apps/reviews/templates/reviews/confirm_delete_metric.html
<div class="modal-header">
  <div class="row">
    <div class="col-xs-3 modal-action-left">
      <a href="#" class="btn" data-dismiss="modal"><i class="fa fa-chevron-left"></i> <span>Cancel</span></a>
    </div>
    <div class="col-xs-6">
      <h4 class="modal-title text-center" id="myModalLabel">Confirm Delete Metric</h4>
    </div>
    <div class="col-xs-3 modal-action-right">
      <a href="#" class="btn" data-dismiss="modal" onClick="$('#confirmedDeleteMetricForm').submit();"><i class="fa fa-check"></i> Delete</a>
    </div>
  </div>
</div>
<div class="modal-body">
    <form id="confirmedDeleteMetricForm" action="{% url 'metrics:delete' metric.id %}" method="post">
        {% csrf_token %}
    </form>
    <p>
    Are you sure you want to delete
    <strong>{{ metric }}</strong>
    </p>
</div>

apps/reviews/templates/reviews/create.html
{% pjaxr_extends "base_template.html" "Site" %}
{% load crispy_forms_tags %}
{% load review_tags %}
{% block title %}Review organization - {{ current_tenant.name }}{% endblock %}

{% block page_title %}<span id="page-title">Post a review</span>{% endblock %}

{% block left_nav_button %}
  <span id="left-nav-btn" class="pull-left">
    {% if previous_page %}
      <a class="navbar-brand btn" href="{{ previous_page }}"><i class="fa fa-chevron-left"></i><!--  <span>Cancel</span> --></a>
    {% else %}
      <a class="navbar-brand btn" href="{% url 'home' %}"><i class="fa fa-chevron-left"></i><!--  <span>Cancel</span> --></a>
    {% endif %}
  </span>
{% endblock %}

{% block right_nav_button %}
  <span id="right-nav-btn" class="pull-right">
    <a class="navbar-brand btn" href="#"> <span>Post</span></a>
  </span>
{% endblock %}

{% block right_sidebar %}
  <div id="sidebar-right" class="sidebar sidebar-right"></div>
{% endblock %}

{% block notifications %}
  {% include 'partials/notifications.html' %}
{% endblock %}

{% block page %}
  <div id="page" class="container page">
    {% block content %}
      <section>
        <h6 class="section-title text-uppercase">Post a review</h6>
        <div class="panel panel-default panel-card">
          <div class="panel-body">


            <div class="col-md-8 col-md-offset-2">
              <h4 class="section-title text-center">You are reviewing <a href="{{ content_object.get_absolute_url }} " class="no-underline no-link-style"><b>{{ content_object }}</b></a></h4>
              <br>
              {% if weight_sum_ok %}
                <form class="form-mobile clearfix" action="{%if public_review%}{% url 'reviews:public_review' uuid %}{% else %}{% get_review_url 'add' content_object %}{% endif %}" method="POST">
                  {% csrf_token %}
                  {% include 'forms/naked_form.html' with form=form field_template_name="bootstrap3" %}
                  <div class="text-center form-actions col-xs-12">
                    <button type="submit" class="btn btn-primary">Post your review</button>
                  </div>
                  <br><br>
                </form>
              {% else %}
                <br><br><!-- We should not need to do this just to get margins right. [MN]-->
                <div class="alert alert-danger text-center">
                  <h4>Oops! Review cannot be created, as the metric weights do not add up.</h4>
                  <h5>
                    {% if perms.reviews.add_metric %}
                    <a href="{% url 'client_settings:metrics_list' content_type.id %}?previous_page={{ request.get_full_path }}" class="btn btn-primary">edit metrics now</a>
                    {% else %}
                        Contact the admin of this account at your organization to get this sorted out.
                    {% endif %}
                  </h5>
                </div>
              {% endif %}
            </div>

          </div>
        </div>
      </section>


<!-- 
      <div class="page-top-band">
        <div class="col-xs-12">
          <h6>Post a review for {{ content_object }} ({{ content_type }})</h6>
        </div>
      </div> -->
    {% endblock %}
  </div>
{% endblock %}
{% block pjaxr_namespace %}Site.projects_review{% endblock pjaxr_namespace %}

apps/reviews/templates/reviews/create_anonymous_review.html
{% pjaxr_extends "guest_base_extended.html" "Site" %}
{% load crispy_forms_tags %}
{% load review_tags %}
{% block title %}Review organization - {{ current_tenant.name }}{% endblock %}

{% block left_nav_button %}
  <span id="left-nav-btn" class="pull-left">
    {% if previous_page %}
      <a class="navbar-brand btn" href="{{ previous_page }}"><i class="fa fa-chevron-left"></i><!--  <span>Cancel</span> --></a>
    {% else %}
      <a class="navbar-brand btn" href="{% url 'home' %}"><i class="fa fa-chevron-left"></i><!--  <span>Cancel</span> --></a>
    {% endif %}
  </span>
{% endblock %}

{% block right_sidebar %}
  <div id="sidebar-right" class="sidebar sidebar-right"></div>
{% endblock %}

{% block notifications %}
  {% include 'partials/notifications.html' %}
{% endblock %}

{% block page %}
  <div id="page" class="container page">
    {% block content %}
      <section>
        <h6 class="section-title text-uppercase">Post a review</h6>
        <div class="panel panel-default panel-card">
          <div class="panel-body">


            <div class="col-md-8 col-md-offset-2">
              <h4 class="section-title text-center">You are reviewing <a href="{{ content_object.get_absolute_url }} " class="no-underline no-link-style"><b>{{ content_object }}</b></a></h4>
              <br>
              {% if weight_sum_ok %}
                <form class="form-mobile clearfix" action="{% url 'reviews:public_review' uuid %}" method="POST">
                  {% csrf_token %}
                  {% include 'forms/naked_form.html' with form=form field_template_name="bootstrap3" %}
                  <div class="text-center form-actions col-xs-12">
                    <button type="submit" class="btn btn-primary">Post your review</button>
                  </div>
                  <br><br>
                </form>
              {% else %}
                <br><br><!-- We should not need to do this just to get margins right. [MN]-->
                <div class="alert alert-danger text-center">
                  <h4>Oops! Review cannot be created, as the metric weights do not add up.</h4>
                  <h5>
                    {% if perms.reviews.add_metric %}
                    <a href="{% url 'client_settings:metrics_list' content_type.id %}?previous_page={{ request.get_full_path }}" class="btn btn-primary">edit metrics now</a>
                    {% else %}
                        Contact the admin of this account at your organization to get this sorted out.
                    {% endif %}
                  </h5>
                </div>
              {% endif %}
            </div>

          </div>
        </div>
      </section>


<!-- 
      <div class="page-top-band">
        <div class="col-xs-12">
          <h6>Post a review for {{ content_object }} ({{ content_type }})</h6>
        </div>
      </div> -->
    {% endblock %}
  </div>
{% endblock %}
{% block pjaxr_namespace %}Site.projects_review{% endblock pjaxr_namespace %}